### ISSUE TITLE
Dialer causes reboot in 4.0.1

### ISSUE THREAD

**Issue by jhshi** [phonelab/cm-shamu.manifest#1]
Open the dialer and dial a number. The phone will reboot when make a phone call.

**Comment by saintsantos** [comment]
Google dialer bug on the latest gapps. Removed googler dialer and replaced with default dialer.

**Comment by jhshi** [comment]
Not solved. Error log:

```
![screenshot_20160808-135939](https://cloud.githubusercontent.com/assets/1173734/17496183/feb992ea-5d70-11e6-9346-452ddd9182cb.png)
2016-08-08 13:59:30.489.489937579  4976  4976 E DialtactsActivity: java.lang.Exception
2016-08-08 13:59:30.489.489937579  4976  4976 E DialtactsActivity:      at com.android.dialer.DialtactsActivity.onCallMethodChangedListener(DialtactsActivity.java:306)
2016-08-08 13:59:30.489.489937579  4976  4976 E DialtactsActivity:      at com.android.dialer.incall.CallMethodSpinnerHelper.updateCallMethodUI(CallMethodSpinnerHelper.java:139)
2016-08-08 13:59:30.489.489937579  4976  4976 E DialtactsActivity:      at com.android.dialer.dialpad.DialpadFragment.updateSpinner(DialpadFragment.java:519)
2016-08-08 13:59:30.489.489937579  4976  4976 E DialtactsActivity:      at com.android.dialer.dialpad.DialpadFragment.providersUpdated(DialpadFragment.java:486)
2016-08-08 13:59:30.489.489937579  4976  4976 E DialtactsActivity:      at com.android.dialer.DialtactsActivity.onDialpadShown(DialtactsActivity.java:1044)
2016-08-08 13:59:30.489.489937579  4976  4976 E DialtactsActivity:      at com.android.dialer.dialpad.DialpadFragment.onHiddenChanged(DialpadFragment.java:1837)
2016-08-08 13:59:30.489.489937579  4976  4976 E DialtactsActivity:      at android.app.FragmentManagerImpl.showFragment(FragmentManager.java:1308)
2016-08-08 13:59:30.489.489937579  4976  4976 E DialtactsActivity:      at android.app.BackStackRecord.run(BackStackRecord.java:770)
2016-08-08 13:59:30.489.489937579  4976  4976 E DialtactsActivity:      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
2016-08-08 13:59:30.489.489937579  4976  4976 E DialtactsActivity:      at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
2016-08-08 13:59:30.489.489937579  4976  4976 E DialtactsActivity:      at android.os.Handler.handleCallback(Handler.java:739)
2016-08-08 13:59:30.489.489937579  4976  4976 E DialtactsActivity:      at android.os.Handler.dispatchMessage(Handler.java:95)
2016-08-08 13:59:30.489.489937579  4976  4976 E DialtactsActivity:      at android.os.Looper.loop(Looper.java:148)
2016-08-08 13:59:30.489.489937579  4976  4976 E DialtactsActivity:      at android.app.ActivityThread.main(ActivityThread.java:5461)
2016-08-08 13:59:30.489.489937579  4976  4976 E DialtactsActivity:      at java.lang.reflect.Method.invoke(Native Method)
2016-08-08 13:59:30.489.489937579  4976  4976 E DialtactsActivity:      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
2016-08-08 13:59:30.489.489937579  4976  4976 E DialtactsActivity:      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by jhshi** [comment]
Works if clean flash, not OTA.
